[미션2] Textarea 컴포넌트를 구현하라
huskint/learn-frontend-skill pull request #6
Opened 2022-12-21 07:29 UTC by ShinjungOh

- [x] input 스타일 코드를 활용하여 기본 textarea 스타일을 작성해주세요.
- [x] hover했을 경우 테두리색이 변경됩니다.
- [x] readonly의 경우 배경색이 바뀝니다.
- [x] disabled의 경우 배경색과 글자색이 바뀝니다.
- [ ] 세로 5줄 입력이 가능하도록 높이값을 지정해주세요.
- [x] textarea가 resize 되지 않도록 해주세요.
- [x] textarea 내부 스크롤 스타일 변경
- [x] 미션1에서 완료한 useInput hooks를 적용하여 value, onChange 적용해 보세요.

2022-12-21 07:35 UTC, bytrustu requested changes
textarea props 관련 보완해야 될 내용이 있어 리뷰 드립니다. 🤔

2022-12-21 07:35 UTC, bytrustu commented on src/ui/components/common/TextArea.tsx
> +}: TextAreaProps) => (
태그에 기본적으로 사용되는 props 들은 반드시 적어주시는게 좋습니다.
그래야 해당 컴포넌트들을 본인이 아닌 협업을 하는 동료가 사용을 하더라도
어떤 속성을 꼭 입력해주어야 하는지 알 수 있기 때문입니다.

TextArea의 경우 
id, name, rows, placeholder, value, onChange
정도는 직업 타입 및 props를 적용시켜주세요.

...props로 적용되는 사항들은
나머지 property들을 적용해주는 보완 작업이라고 생각해주시면 됩니다.

우리가 같이 하나씩 만들어보고 학습하는 목적은
동작하는것을 구현해보는 것 아니라 
"확실하게 잘" 구현하는 것 입니다.

2022-12-21 18:38 UTC, ShinjungOh commented on src/ui/components/common/TextArea.tsx
> +}: TextAreaProps) => (
id, name, rows, placeholder, value, onChange 등 TextArea props 보완, 적용해서 다시 커밋했습니다.

작업하면서 어려웠던 점이 rows를 적용하는 것이었는데요,
구글링 해보니 width, height를 적용하면 rows를 사용할 수 없다고 해서 이 부분은 적용하지 않았습니다.
```rows={5}``` 와 같이 적용하는걸로 알고 있는데 이 부분이 제가 만든 TextArea에서는 적용되지 않아서 도움 주시면 감사하겠습니다!

2022-12-22 03:41 UTC, bytrustu commented on src/ui/components/common/TextArea.tsx
> +}: TextAreaProps) => (
Textarea rows와 style 관계에 대해서 잘 조사해보셨네요!
말씀해주신것처럼 style이 적용되어져 있으면 크기가 고정되어 rows, cols가 적용이 안될수 있습니다.
작업해주신 내용을 확인해보니
TextArea에 padding이 걸려있네요.
![image](https://user-images.githubusercontent.com/39726717/209050549-874d361a-69c8-4099-b451-d80dfa3ef698.png)

padding이 bottom에도 적용이 되어 있어 rows={5} 를 표기하였지만 6줄로 표시가 되고 있네요.
padding-bottom은 0이나 값을 조정 해주는것이 좋을것 같은데 어떻게 생각하시나요?

2022-12-22 03:44 UTC, bytrustu reviewed
컴포넌트 네이밍 대소문자 관련하여 추가적으로 수정 제안 드립니다.

2022-12-22 03:44 UTC, bytrustu commented on src/ui/components/common/TextArea.tsx
> +const TextArea = ({
TextArea로 네이밍을 해주셨네요.
Textarea로 변경하는게 어떨까 싶습니다.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea

2022-12-22 05:17 UTC, ShinjungOh commented on src/ui/components/common/TextArea.tsx
> +const TextArea = ({
파일명과 컴포넌트 이름을 동일하게 하면 오류가 나서 부득히하게 파일명을 TextArea로 수정했습니다. 
css 부분 보완해 다시 푸시해두었습니다.

2022-12-22 05:23 UTC, ShinjungOh commented on src/ui/components/common/TextArea.tsx
> +const TextArea = ({
파일명, 컴포넌트명 수정했습니다!

2022-12-22 06:30 UTC, bytrustu approved these changes
수고했습니다!
리뷰 내용 모두 반영해주셔서 감사합니다. 🙇‍♂️

2022-12-22 06:43 UTC, ShinjungOh commented on src/ui/components/common/TextArea.tsx
> +}: TextAreaProps) => (
padding-bottom 0으로 주어 조정했습니다!

2022-12-22 06:44 UTC, merged